import React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import '@fontsource-variable/open-sans'
import '@fontsource-variable/spline-sans'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
